apiVersion: v1
kind: ReplicationController
metadata:
  name: phpinfo
spec:
  replicas: 2
  selector:
    app: phpinfo
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      - name: phpinfo
        image: academiaonline/phpinfo:latest
